server:
  port: 7001

spring:
  application:
    name: microservice-zuul-gateway

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
    instance:
      instance-id: ${spring.application.name}:${server.port} #实例id,指定eureka页面服务状态显示
      prefer-ip-address: true #指定鼠标悬停在实例id上显示ip地址
#zuul路由配置
zuul:
  routes:
    provider-product:
      path: /product/** #访问路径
      serviceId: microservice-product #指定服务的id,会自动从eureka中找到该服务的ip和端口号
      stripPrefix: false #代理转发时去掉前缀,false为不去掉前缀
