server:
  port: 5001
spring:
  application:
    name: microservice-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FangYanFor1994/microservice-cloud-config.git
          username: FangYanFor1994
          password: fangyan1994!
          skip-ssl-validation: true